// Nombres legibles de las acciones del registro de auditoria (2026-09-07):
// la ruta de la API traducida a lo que hizo la persona. Lo que no figura se
// muestra como METODO /ruta.

const ACCIONES: [RegExp, string][] = [
  [/^POST \/auth\/login$/, 'Inicio de sesión'],
  [/^POST \/auth\/logout$/, 'Cierre de sesión'],
  [/^POST \/users\/me\/password$/, 'Cambio de la propia contraseña'],
  [/^POST \/users$/, 'Alta de cuenta de acceso'],
  [/^PATCH \/users\/:id$/, 'Edición de cuenta de acceso'],
  [/^DELETE \/users\/:id$/, 'Eliminación de cuenta de acceso'],
  [/^POST \/users\/:id\/reset-password$/, 'Reinicio de contraseña de un usuario'],
  [/^POST \/customers$/, 'Alta de cliente'],
  [/^PATCH \/customers\/:id$/, 'Edición de cliente'],
  [/^DELETE \/customers\/:id$/, 'Desactivación de cliente'],
  [/^POST \/customers\/:id\/merge$/, 'Unión de fichas de clientes'],
  [/^POST \/customers\/:id\/fiscal-ids$/, 'Alta de RUC/razón social del cliente'],
  [/^PATCH \/customers\/:id\/fiscal-ids\/:fid$/, 'Edición de RUC/razón social del cliente'],
  [/^DELETE \/customers\/:id\/fiscal-ids\/:fid$/, 'Baja de RUC/razón social del cliente'],
  [/^POST \/customers\/:id\/charges$/, 'Consumo agregado a la cuenta del mes'],
  [/^POST \/customers\/:id\/contact-points$/, 'Alta de contacto del cliente'],
  [/^POST \/customers\/:id\/activities$/, 'Nota o tarea en la ficha'],
  [/^POST \/appointments$/, 'Turno agendado'],
  [/^POST \/appointments\/:id\/confirm$/, 'Turno confirmado'],
  [/^POST \/appointments\/:id\/cancel$/, 'Turno cancelado'],
  [/^POST \/appointments\/:id\/complete$/, 'Turno marcado atendido'],
  [/^POST \/appointments\/:id\/no-show$/, 'Turno marcado "no vino"'],
  [/^POST \/appointments\/:id\/reschedule$/, 'Turno reprogramado'],
  [/^POST \/recurring-bookings$/, 'Servicio recurrente creado'],
  [/^PATCH \/recurring-bookings\/:id$/, 'Servicio recurrente editado'],
  [/^DELETE \/recurring-bookings\/:id$/, 'Servicio recurrente quitado'],
  [/^POST \/catalog\/categories$/, 'Categoría creada'],
  [/^PATCH \/catalog\/categories\/:id$/, 'Categoría editada'],
  [/^DELETE \/catalog\/categories\/:id$/, 'Categoría eliminada'],
  [/^POST \/catalog\/services$/, 'Producto creado'],
  [/^PATCH \/catalog\/services\/:id$/, 'Producto editado'],
  [/^DELETE \/catalog\/services\/:id$/, 'Producto eliminado'],
  [/^POST \/catalog\/import$/, 'Carga masiva del catálogo'],
  [/^POST \/invoices$/, 'Borrador de factura creado'],
  [/^POST \/invoices\/:id\/issue$/, 'Factura emitida'],
  [/^POST \/invoices\/:id\/cancel$/, 'Factura anulada'],
  [/^POST \/invoices\/:id\/payments$/, 'Pago registrado'],
  [/^PATCH \/invoices\/:id\/billing$/, 'Receptor de la factura cambiado'],
  [/^DELETE \/invoices\/:id$/, 'Borrador de factura borrado'],
  [/^POST \/invoices\/:id\/send$/, 'Factura enviada al cliente'],
  [/^POST \/quotes$/, 'Presupuesto creado'],
  [/^PATCH \/quotes\/:id$/, 'Presupuesto editado'],
  [/^POST \/quotes\/:id\/invoice$/, 'Presupuesto convertido en factura'],
  [/^DELETE \/quotes\/:id$/, 'Presupuesto borrado'],
  [/^POST \/billing\/accounts\/:customerId\/invoice$/, 'Cuenta del mes facturada'],
  [/^POST \/billing\/accounts\/:customerId\/notify$/, 'Resumen de cuenta enviado'],
  [/^POST \/billing\/close-month$/, 'Cierre de mes a pedido'],
  [/^DELETE \/billing\/charges\/:id$/, 'Consumo anulado'],
  [/^POST \/employees$/, 'Alta de empleado'],
  [/^POST \/employees\/:id\/absences$/, 'Ausencia de empleado registrada'],
  [/^DELETE \/employees\/:id\/absences\/:absenceId$/, 'Ausencia de empleado quitada'],
  [/^PATCH \/employees\/:id$/, 'Edición de empleado'],
  [/^DELETE \/employees\/:id$/, 'Baja de empleado'],
  [/^PUT \/employees\/form-settings$/, 'Campos obligatorios de la ficha'],
  [/^PATCH \/tenant$/, 'Datos de la empresa'],
  [/^PUT \/tenant\/settings$/, 'Ajustes del negocio'],
  [/^PATCH \/bot\/settings$/, 'Ajustes del bot'],
  [/^PUT \/branches\/:id\/schedule$/, 'Horarios de atención'],
  [/^PATCH \/branches\/:id$/, 'Sucursal editada'],
  [/^PUT \/integrations\/whatsapp$/, 'Conexión de WhatsApp'],
  [/^PUT \/integrations\/sifen$/, 'Datos de facturación electrónica'],
  [/^POST \/integrations\/google\/connect$/, 'Conexión de Google Calendar iniciada'],
  [/^DELETE \/integrations\/google_calendar$/, 'Google Calendar desconectado'],
  [/^POST \/conversations\/:id\/messages$/, 'Mensaje enviado por chat'],
  [/^POST \/conversations\/:id\/(pause|resume|close)$/, 'Estado de la conversación'],
  [/^POST \/conversations\/:id\/link-customer$/, 'Conversación vinculada a cliente'],
  [/^POST \/custom-fields$/, 'Campo personalizado creado'],
  [/^POST \/platform\/tenants$/, 'Alta de cliente (plataforma)'],
  [/^PATCH \/platform\/tenants\/:id$/, 'Ficha de cliente editada (plataforma)'],
  [/^PUT \/platform\/tenants\/:id\/bot-budget$/, 'Presupuesto de IA del cliente'],
  [/^POST \/platform\/tenants\/:id\/users\/:userId\/reset-password$/, 'Reinicio de contraseña de un usuario del cliente'],
  [/^PUT \/platform\/tenants\/:id\/overrides$/, 'Acuerdo a medida'],
  [/^DELETE \/platform\/tenants\/:id\/overrides\/:featureCode$/, 'Acuerdo a medida quitado'],
  [/^POST \/platform\/plans$/, 'Plan creado'],
  [/^PATCH \/platform\/plans\/:id$/, 'Plan editado'],
  [/^PUT \/platform\/settings\/bot$/, 'Motor del bot (IA)'],
  [/^PUT \/platform\/settings\/security$/, 'Ajustes de seguridad'],
  [/^PUT \/platform\/settings\/google$/, 'App de Google'],
  [/^PUT \/platform\/settings\/mail$/, 'Correo saliente'],
  [/^POST \/platform\/settings\/mail\/test$/, 'Correo de prueba'],
  [/^POST \/platform\/users$/, 'Alta de usuario del portal'],
  [/^PATCH \/platform\/users\/:id$/, 'Usuario del portal editado'],
  [/^POST \/platform\/users\/:id\/reset-password$/, 'Reinicio de contraseña de usuario del portal'],
  [/^PATCH \/platform\/me$/, 'Mi perfil (plataforma)'],
  [/^POST \/platform\/me\/password$/, 'Cambio de la propia contraseña (plataforma)'],
  [/^POST \/platform\/assistant$/, 'Consulta al asistente de soporte'],
];

export function describirAccion(method: string, route: string | null, path: string): string {
  const clave = `${method} ${route ?? path}`;
  for (const [re, label] of ACCIONES) if (re.test(clave)) return label;
  return `${method} ${route ?? path}`;
}

/** Nombre legible de una tabla auditada. */
export const ENTIDAD: Record<string, string> = {
  customers: 'Cliente',
  appointments: 'Turno',
  appointment_services: 'Servicio del turno',
  services: 'Producto',
  service_categories: 'Categoría',
  invoices: 'Factura',
  invoice_items: 'Ítem de factura',
  payments: 'Pago',
  quotes: 'Presupuesto',
  users: 'Cuenta de acceso',
  employees: 'Empleado',
  bot_settings: 'Ajustes del bot',
  tenant_settings: 'Ajustes del negocio',
  integration_credentials: 'Integración',
  customer_fiscal_ids: 'RUC / razón social',
  customer_charges: 'Consumo',
  billing_statements: 'Cierre de mes',
  recurring_bookings: 'Servicio recurrente',
  customer_contact_points: 'Contacto del cliente',
  customer_activities: 'Nota o tarea',
  custom_field_defs: 'Campo personalizado',
  service_photos: 'Foto de producto',
  employee_form_settings: 'Campos obligatorios de la ficha',
  employee_absences: 'Ausencia de empleado',
};

/** Etiquetas de columnas frecuentes en los "antes / después". */
export const CAMPO: Record<string, string> = {
  status: 'estado',
  first_name: 'nombre',
  last_name: 'apellido',
  phone_e164: 'celular',
  email: 'email',
  doc_number: 'documento',
  starts_at: 'inicio',
  ends_at: 'fin',
  employee_id: 'profesional',
  service_id: 'servicio',
  price: 'precio',
  total: 'total',
  notes: 'notas',
  is_active: 'activo',
  role: 'rol',
  full_name: 'nombre completo',
  legal_name: 'razón social',
  billing_name: 'facturada a',
  cancel_reason: 'motivo de anulación',
  last_login_at: 'último acceso',
  updated_at: 'actualizado',
  created_at: 'creado',
};
